import type { Activity } from '../types/activities';

// Fixed rewards: a flat point value per completion
export const fixedRewardActivities: Activity[] = [
  {
    id: 'cafe-trip',
    name: 'Cafe trip',
    type: 'fixed',
    points: 1,
    requiresProject: false,
    emoji: '☕',
  },
  {
    id: 'new-restaurant',
    name: 'Try new restaurant',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🍝',
  },
  {
    id: 'make-fancy-drink',
    name: 'Make fancy drink',
    type: 'fixed',
    points: 1,
    requiresProject: false,
    emoji: '🍸',
  },
  {
    id: 'apply-to-something',
    name: 'Apply to something',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '📝',
  },
  {
    id: 'watch-movie-at-home',
    name: 'Watch movie at home',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🎬',
  },
  {
    id: 'paint-nails',
    name: 'Paint nails',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '💅',
  },
  {
    id: 'attend-appointment',
    name: 'Attend appointment',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '📅',
  },
  {
    id: 'listen-new-album',
    name: 'Listen to new album',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🎧',
  },
  {
    id: 'clear-emails-desktop',
    name: 'Clear emails & desktop',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '📥',
  },
  {
    id: 'get-hit-on',
    name: 'Get hit on',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🙁',
  },
  {
    id: 'post-instagram-carousel',
    name: 'Post Instagram carousel',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '📸',
  },
  {
    id: 'post-tiktok',
    name: 'Post Tiktok',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '📱',
  },
  {
    id: 'bake',
    name: 'Bake',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '👩‍🍳',
  },
  {
    id: 'picnic',
    name: 'Picnic',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🧺',
  },
  {
    id: 'pool-day',
    name: 'Pool day',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🏊‍♀️',
  },
  {
    id: 'mall-trip',
    name: 'Mall trip',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🛍️',
  },
  {
    id: 'deep-clean-room',
    name: 'Deep clean room/bathroom',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🧹',
  },
  {
    id: 'watch-sunrise',
    name: 'Watch sunrise',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🌅',
  },
  {
    id: 'do-full-beat',
    name: 'Full beat',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '💄',
  },
  {
    id: 'digi-photoshoot',
    name: 'Digi photoshoot',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '📷',
  },
  {
    id: 'go-to-theater',
    name: 'Go to theater',
    type: 'fixed',
    points: 4,
    requiresProject: false,
    emoji: '🎭',
  },
  {
    id: 'post-youtube-video',
    name: 'Post YouTube video',
    type: 'fixed',
    points: 5,
    requiresProject: false,
    emoji: '🎥',
  },
  {
    id: 'big-purchase',
    name: 'Big purchase',
    type: 'fixed',
    points: 4,
    requiresProject: false,
    emoji: '💳',
  },
  {
    id: 'travel-to-other-state',
    name: 'Travel to other state',
    type: 'fixed',
    points: 5,
    requiresProject: false,
    emoji: '✈️',
  },
  {
    id: 'travel-to-other-city',
    name: 'Travel to other city',
    type: 'fixed',
    points: 4,
    requiresProject: false,
    emoji: '🚗',
  },
  {
    id: 'clothes-shopping',
    name: 'Clothes shopping',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '👗',
  },
  {
    id: 'vintage-market',
    name: 'Vintage/farmers market',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🧺',
  },
  {
    id: 'linkedin',
    name: '+25 LinkedIn connections',
    type: 'fixed',
    points: 1,
    requiresProject: false,
    emoji: '👤',
  },
  {
    id: 'attend-workshop',
    name: 'Attend workshop',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🛠️'
  },
  {
    id: 'museum-trip',
    name: 'Museum trip',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🏛️',
  },
  {
    id: 'take-hike',
    name: 'Take hike',
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🏕️',
  },
  {
    id: 'gift-something',
    name: 'Gift something',
    type: 'fixed',
    points: 2,
    requiresProject: false,
    emoji: '🎁',
  },
  {
    id: 'get-contact-info',
    name: "Get stranger Insta/number",
    type: 'fixed',
    points: 3,
    requiresProject: false,
    emoji: '🫂',
  },
  {
    id: 'host-community-event',
    name: "Host community event",
    type: 'fixed',
    points: 5,
    requiresProject: false,
    emoji: '🌍',
  },
  {
    id: 'attend-tech-meetup',
    name: "Attend local tech meetup",
    type: 'fixed',
    points: 4,
    requiresProject: false,
    emoji: '🤖',
  }
];