import type { Activity } from '../types/activities';

// Fixed detractors: a flat (negative) point value per occurrence
export const fixedDetractorActivities: Activity[] = [
  {
    id: 'ghost-texts-12h',
    name: 'Ghost texts for 12 hours',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '👻',
  },
  {
    id: 'lose-a-bet',
    name: 'Lose a bet',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '🎰',
  },
  {
    id: 'cancel-plans',
    name: 'Cancel plans',
    type: 'fixed',
    points: -4,
    requiresProject: false,
    emoji: '❌',
  },
  {
    id: 'bad-purchase',
    name: 'Bad purchase',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '💸',
  },
  {
    id: 'messy-room-1-day',
    name: '1 day messy room',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '🧺',
  },
  {
    id: 'late-on-work-1-day',
    name: '1 day late on work',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '⏰',
  },
  {
    id: 'answer-talking-stage',
    name: 'Answer talking stage',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '🤡',
  },
  {
    id: 'cry',
    name: 'Cry',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '😭',
  },
  {
    id: 'sick-1-day',
    name: '1 day sick',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '🤒',
  },
  {
    id: 'get-caught-lying',
    name: 'Get caught lying',
    type: 'fixed',
    points: -5,
    requiresProject: false,
    emoji: '🤥',
  },
  {
    id: 'fail-a-test',
    name: 'Fail a test',
    type: 'fixed',
    points: -5,
    requiresProject: false,
    emoji: '📉',
  },
  {
    id: 'sleep-though',
    name: 'Sleep through meeting/event',
    type: 'fixed',
    points: -5,
    requiresProject: false,
    emoji: '💤',
  },
  {
    id: 'doomscroll',
    name: 'Doomscroll 30+ min',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '📱',
  },
  {
    id: 'nighttime-code',
    name: 'Code at 1am (why)',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '🫩',
  },
  {
    id: 'long-nap',
    name: '2+ hour nap',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '🛏️',
  },
  {
    id: 'isolate',
    name: 'Isolate for 1 week',
    type: 'fixed',
    points: -3,
    requiresProject: false,
    emoji: '🧑‍🧑‍🧒‍🧒',
  },
  {
    id: 'one-meal-day',
    name: 'Eat one meal in day',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '🍽️',
  },
  {
    id: 'forget-water',
    name: 'Forget water for day',
    type: 'fixed',
    points: -2,
    requiresProject: false,
    emoji: '💧',
  },
  {
    id: 'sibling-fight',
    name: 'Sibling fight',
    type: 'per_hour',
    points: -2,
    requiresProject: true,
    emoji: '👭',
  }
];